version: "3.7"

services:
  site:
    image: gitlab.gitiserver.com:5555/lumber-click/site:latest
    environment:
      ENV_SILENT: "true"
      HOST: "0.0.0.0"
      PORT: 3000
      NODE_ENV: "development"
      APP_URL: "http://${HOST}:${PORT}"
      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: lumber_click
      DB_USER: lumber_click
      DB_PASSWORD: 123Lumber.Click321
    ports:
      - "64050:3000"

  postgres:
    image: matno/postgres-postgis:11
    environment:
      POSTGRES_DB: lumber_click
      POSTGRES_USER: lumber_click
      POSTGRES_PASSWORD: 123Lumber.Click321
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
